[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../crates/common" }
disease_detection = { path = "../crates/disease_detection" }
tokio = { workspace = true }
actix-web = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dotenv = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

